require('dotenv').config();
const express=require('express'); const cors=require('cors'); const jwt=require('jsonwebtoken'); const crypto=require('crypto'); const {Pool}=require('pg');
const app=express(); const PORT=Number(process.env.PORT||3000); const JWT_SECRET=process.env.JWT_SECRET||'CHANGE_ME';
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==='true'?{rejectUnauthorized:false}:false,max:Number(process.env.DB_POOL_MAX||10)});
const allowedOrigins=(process.env.CORS_ORIGIN||'*').split(',').map(x=>x.trim()); app.use(cors({origin:(origin,cb)=>{if(!origin||allowedOrigins.includes('*')||allowedOrigins.includes(origin))return cb(null,true);cb(new Error('Origin non autorisée'))}})); app.use(express.json({limit:'1mb'}));
const hash=p=>crypto.scryptSync(p,process.env.PASSWORD_SALT||'tontine-digital-salt',64).toString('hex');
const token=u=>jwt.sign({id:u.id,role:u.role},JWT_SECRET,{expiresIn:'7d'});
const ok=(res,data)=>res.json(data); const bad=(res,c,e)=>res.status(c).json({error:e});
async function q(text,params=[]){return pool.query(text,params)}
async function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw 0;req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch{bad(res,401,'Non authentifié')}}
function role(...roles){return (req,res,next)=>roles.includes(req.user.role)?next():bad(res,403,'Accès interdit')}
async function audit(actor,action,type,id,metadata={}){await q('INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,$3,$4,$5)',[actor,action,type,id,metadata])}
app.get('/api/health',async(req,res)=>{try{await q('SELECT 1');ok(res,{ok:true,database:true})}catch(e){bad(res,503,'Base de données indisponible')}});
app.post('/api/auth/register',async(req,res)=>{try{const {name,dob,phone,email,password,referralCode}=req.body||{};if(!name||!dob||!phone||!password)return bad(res,400,'Champs obligatoires manquants');if(password.length<8)return bad(res,400,'Mot de passe: 8 caractères minimum');let ref=null;if(referralCode){const r=await q('SELECT id FROM users WHERE referral_code=$1',[referralCode.trim()]);if(!r.rowCount)return bad(res,400,'Code parrain invalide');ref=r.rows[0].id}const id=crypto.randomUUID(),code='TD-'+crypto.randomBytes(4).toString('hex').toUpperCase();const r=await q('INSERT INTO users(id,full_name,birth_date,phone,email,password_hash,referral_code,referred_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,full_name,birth_date,phone,email,referral_code,role',[id,name,dob,phone,email||null,hash(password),code,ref]);const u=r.rows[0];await audit(u.id,'REGISTER','USER',u.id);res.status(201).json({user:u,token:token(u)})}catch(e){if(e.code==='23505')return bad(res,409,'Téléphone ou email déjà utilisé');bad(res,500,'Erreur serveur')}});
app.post('/api/auth/login',async(req,res)=>{try{const {identifier,password}=req.body||{};const r=await q('SELECT * FROM users WHERE phone=$1 OR email=$1',[identifier]);if(!r.rowCount||hash(password)!==r.rows[0].password_hash)return bad(res,401,'Identifiants invalides');const u=r.rows[0];delete u.password_hash;res.json({user:u,token:token(u)})}catch(e){bad(res,500,'Erreur serveur')}});
app.get('/api/me',auth,async(req,res)=>{const r=await q('SELECT id,full_name,birth_date,phone,email,referral_code,role,created_at FROM users WHERE id=$1',[req.user.id]);if(!r.rowCount)return bad(res,404,'Utilisateur introuvable');ok(res,r.rows[0])});
app.get('/api/tontines',auth,async(req,res)=>{const r=await q('SELECT t.*,COUNT(tm.user_id)::int member_count FROM tontines t LEFT JOIN tontine_members tm ON tm.tontine_id=t.id GROUP BY t.id ORDER BY t.created_at DESC');ok(res,r.rows)});
app.post('/api/tontines/:id/join',auth,async(req,res)=>{const c=await pool.connect();try{await c.query('BEGIN');const t=await c.query('SELECT * FROM tontines WHERE id=$1 AND status=\'ACTIVE\' FOR UPDATE',[req.params.id]);if(!t.rowCount)throw new Error('Tontine introuvable ou inactive');const exists=await c.query('SELECT 1 FROM tontine_members WHERE tontine_id=$1 AND user_id=$2',[req.params.id,req.user.id]);if(exists.rowCount)throw new Error('Déjà membre');const p=await c.query('SELECT COALESCE(MAX(position_no),0)+1 position FROM tontine_members WHERE tontine_id=$1',[req.params.id]);await c.query('INSERT INTO tontine_members(tontine_id,user_id,position_no) VALUES($1,$2,$3)',[req.params.id,req.user.id,p.rows[0].position]);await c.query('COMMIT');await audit(req.user.id,'JOIN','TONTINE',req.params.id);ok(res,{ok:true,position:p.rows[0].position})}catch(e){await c.query('ROLLBACK');bad(res,400,e.message)}finally{c.release()}});
app.post('/api/payments/preview',auth,async(req,res)=>{try{const {tontineId}=req.body||{};const r=await q('SELECT t.contribution_amount,EXISTS(SELECT 1 FROM payments p WHERE p.user_id=$1 AND p.tontine_id=t.id AND p.status=\'CONFIRMED\') has_paid,u.referred_by FROM tontines t JOIN users u ON u.id=$1 WHERE t.id=$2',[req.user.id,tontineId]);if(!r.rowCount)return bad(res,404,'Tontine introuvable');const x=r.rows[0],first=!x.has_paid,admin=first?Math.floor(Number(x.contribution_amount)*.01):0,sponsor=first&&x.referred_by?Math.floor(Number(x.contribution_amount)*.01):0;ok(res,{baseAmount:Number(x.contribution_amount),adminCommission:admin,sponsorCommission:sponsor,totalAmount:Number(x.contribution_amount)+admin+sponsor,firstContribution:first})}catch(e){bad(res,500,'Erreur serveur')}});
app.post('/api/payments',auth,async(req,res)=>{const c=await pool.connect();try{const {tontineId,idempotencyKey,provider}=req.body||{};if(!idempotencyKey)return bad(res,400,'Idempotency-Key requis');await c.query('BEGIN');const old=await c.query('SELECT * FROM payments WHERE idempotency_key=$1',[idempotencyKey]);if(old.rowCount){await c.query('ROLLBACK');return ok(res,old.rows[0])}const t=await c.query('SELECT t.contribution_amount,u.referred_by FROM tontines t JOIN tontine_members tm ON tm.tontine_id=t.id AND tm.user_id=$1 JOIN users u ON u.id=$1 WHERE t.id=$2 AND t.status=\'ACTIVE\' FOR UPDATE',[req.user.id,tontineId]);if(!t.rowCount)throw new Error('Vous n’êtes pas membre de cette tontine');const p=await c.query('SELECT EXISTS(SELECT 1 FROM payments WHERE user_id=$1 AND tontine_id=$2 AND status IN(\'CONFIRMED\',\'PENDING\')) has_paid',[req.user.id,tontineId]);const first=!p.rows[0].has_paid,base=Number(t.rows[0].contribution_amount),admin=first?Math.floor(base*.01):0,sponsor=first&&p.rows[0].referred_by?Math.floor(base*.01):0,total=base+admin+sponsor;const ins=await c.query('INSERT INTO payments(user_id,tontine_id,base_amount,admin_commission,sponsor_commission,total_amount,status,provider,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,\'PENDING\',$7,$8) RETURNING *',[req.user.id,tontineId,base,admin,sponsor,total,provider||'MANUAL',idempotencyKey]);await c.query('COMMIT');await audit(req.user.id,'CREATE','PAYMENT',ins.rows[0].id,{total});ok(res,ins.rows[0])}catch(e){await c.query('ROLLBACK');bad(res,400,e.message)}finally{c.release()}});
app.get('/api/payments',auth,async(req,res)=>{const r=await q('SELECT p.*,t.name tontine_name FROM payments p JOIN tontines t ON t.id=p.tontine_id WHERE p.user_id=$1 ORDER BY p.created_at DESC',[req.user.id]);ok(res,r.rows)});
app.get('/api/payments/:id/receipt',auth,async(req,res)=>{const r=await q('SELECT p.*,t.name tontine_name,u.full_name,u.phone FROM payments p JOIN tontines t ON t.id=p.tontine_id JOIN users u ON u.id=p.user_id WHERE p.id=$1 AND p.user_id=$2 AND p.status=\'CONFIRMED\'',[req.params.id,req.user.id]);if(!r.rowCount)return bad(res,404,'Reçu indisponible');ok(res,{receipt:r.rows[0]})});
app.get('/api/notifications',auth,async(req,res)=>{const r=await q('SELECT * FROM notifications WHERE user_id=$1 ORDER BY created_at DESC',[req.user.id]);ok(res,r.rows)});
app.get('/api/tontines/:id/messages',auth,async(req,res)=>{const r=await q('SELECT m.*,u.full_name FROM messages m JOIN users u ON u.id=m.user_id JOIN tontine_members tm ON tm.tontine_id=m.tontine_id AND tm.user_id=$2 WHERE m.tontine_id=$1 ORDER BY m.created_at ASC',[req.params.id,req.user.id]);ok(res,r.rows)});
app.post('/api/tontines/:id/messages',auth,async(req,res)=>{const {body}=req.body||{};if(!body)return bad(res,400,'Message vide');const m=await q('INSERT INTO messages(tontine_id,user_id,body) SELECT $1,$2,$3 WHERE EXISTS(SELECT 1 FROM tontine_members WHERE tontine_id=$1 AND user_id=$2) RETURNING *',[req.params.id,req.user.id,body.trim()]);if(!m.rowCount)return bad(res,403,'Vous n’êtes pas membre');ok(res,m.rows[0])});
// ADMIN
app.get('/api/admin/overview',auth,role('admin','super_admin'),async(req,res)=>{const r=await q("SELECT (SELECT COUNT(*) FROM users WHERE role='member') members,(SELECT COUNT(*) FROM tontines) tontines,(SELECT COALESCE(SUM(base_amount),0) FROM payments WHERE status='CONFIRMED') contributions,(SELECT COALESCE(SUM(admin_commission+sponsor_commission),0) FROM payments WHERE status='CONFIRMED') commissions");ok(res,r.rows[0])});
app.get('/api/admin/users',auth,role('admin','super_admin'),async(req,res)=>ok(res,(await q("SELECT id,full_name,birth_date,phone,email,referral_code,role,created_at FROM users ORDER BY created_at DESC")).rows));
app.get('/api/admin/tontines',auth,role('admin','super_admin'),async(req,res)=>ok(res,(await q('SELECT t.*,COUNT(tm.user_id)::int member_count FROM tontines t LEFT JOIN tontine_members tm ON tm.tontine_id=t.id GROUP BY t.id ORDER BY t.created_at DESC')).rows));
app.post('/api/admin/tontines',auth,role('admin','super_admin'),async(req,res)=>{const {name,contributionAmount,frequency,startDate,endDate}=req.body||{};if(!name||!contributionAmount||!frequency||!startDate)return bad(res,400,'Champs obligatoires');const r=await q('INSERT INTO tontines(name,contribution_amount,frequency,start_date,end_date) VALUES($1,$2,$3,$4,$5) RETURNING *',[name,contributionAmount,frequency,startDate,endDate||null]);await audit(req.user.id,'CREATE','TONTINE',r.rows[0].id);ok(res,r.rows[0])});
app.get('/api/admin/payments',auth,role('admin','super_admin'),async(req,res)=>ok(res,(await q('SELECT p.*,u.full_name,u.phone,t.name tontine_name FROM payments p JOIN users u ON u.id=p.user_id JOIN tontines t ON t.id=p.tontine_id ORDER BY p.created_at DESC')).rows));
app.get('/api/admin/ledger',auth,role('admin','super_admin'),async(req,res)=>ok(res,(await q('SELECT l.*,t.name tontine_name FROM ledger_entries l JOIN tontines t ON t.id=l.tontine_id ORDER BY l.created_at DESC')).rows));
app.get('/api/admin/collection-accounts',auth,role('admin','super_admin'),async(req,res)=>ok(res,(await q('SELECT * FROM collection_accounts ORDER BY created_at DESC')).rows));
app.post('/api/admin/collection-accounts',auth,role('admin','super_admin'),async(req,res)=>{const {provider,label,accountIdentifier}=req.body||{};if(!provider||!label||!accountIdentifier)return bad(res,400,'Champs obligatoires');const r=await q('INSERT INTO collection_accounts(provider,label,account_identifier) VALUES($1,$2,$3) RETURNING *',[provider,label,accountIdentifier]);await audit(req.user.id,'CREATE','COLLECTION_ACCOUNT',r.rows[0].id);ok(res,r.rows[0])});
app.get('/api/admin/beneficiary-payments',auth,role('admin','super_admin'),async(req,res)=>ok(res,(await q('SELECT bp.*,u.full_name,u.phone,t.name tontine_name FROM beneficiary_payments bp JOIN users u ON u.id=bp.beneficiary_user_id JOIN tontines t ON t.id=bp.tontine_id ORDER BY bp.due_date,bp.created_at')).rows));
app.post('/api/admin/beneficiary-payments/:id/approve',auth,role('admin','super_admin'),async(req,res)=>{const r=await q("UPDATE beneficiary_payments SET status='APPROVED',approved_at=now() WHERE id=$1 AND status='PENDING_ADMIN_VALIDATION' RETURNING *",[req.params.id]);if(!r.rowCount)return bad(res,409,'Ordre non validable');await audit(req.user.id,'APPROVE','BENEFICIARY_PAYMENT',r.rows[0].id);ok(res,r.rows[0])});
app.post('/api/admin/beneficiary-payments/:id/reject',auth,role('admin','super_admin'),async(req,res)=>{const r=await q("UPDATE beneficiary_payments SET status='REJECTED',rejection_reason=$2 WHERE id=$1 AND status IN('PREPARED','PENDING_ADMIN_VALIDATION') RETURNING *",[req.params.id,req.body?.reason||'Rejeté']);if(!r.rowCount)return bad(res,409,'Ordre non rejetable');await audit(req.user.id,'REJECT','BENEFICIARY_PAYMENT',r.rows[0].id);ok(res,r.rows[0])});
app.post('/api/admin/beneficiary-payments/:id/mark-paid',auth,role('admin','super_admin'),async(req,res)=>{const {providerReference}=req.body||{};if(!providerReference)return bad(res,400,'Référence fournisseur obligatoire');const r=await q("UPDATE beneficiary_payments SET status='PAID',provider_reference=$2,paid_at=now() WHERE id=$1 AND status IN('APPROVED','PAYMENT_IN_PROGRESS') RETURNING *",[req.params.id,providerReference]);if(!r.rowCount)return bad(res,409,'Ordre non payable');await audit(req.user.id,'MARK_PAID','BENEFICIARY_PAYMENT',r.rows[0].id,{providerReference});ok(res,r.rows[0])});
app.post('/api/admin/beneficiary-payments/:id/confirm',auth,role('admin','super_admin'),async(req,res)=>{const r=await q("UPDATE beneficiary_payments SET status='CONFIRMED',confirmed_at=now() WHERE id=$1 AND status='PAID' RETURNING *",[req.params.id]);if(!r.rowCount)return bad(res,409,'Ordre non confirmable');await audit(req.user.id,'CONFIRM','BENEFICIARY_PAYMENT',r.rows[0].id);ok(res,r.rows[0])});
app.post('/webhooks/wave',async(req,res)=>{if(process.env.WAVE_WEBHOOK_SECRET&&req.headers['x-webhook-secret']!==process.env.WAVE_WEBHOOK_SECRET)return bad(res,401,'Webhook non autorisé');const {providerReference,status}=req.body||{};if(!providerReference)return bad(res,400,'Référence manquante');const c=await pool.connect();try{await c.query('BEGIN');const p=await c.query('SELECT * FROM payments WHERE provider_reference=$1 FOR UPDATE',[providerReference]);if(!p.rowCount){await c.query('ROLLBACK');return res.status(404).json({error:'Paiement introuvable'})}if(p.rows[0].status==='CONFIRMED'){await c.query('COMMIT');return ok(res,{ok:true,duplicate:true})}if(status==='CONFIRMED'){const x=p.rows[0];await c.query("UPDATE payments SET status='CONFIRMED',confirmed_at=now() WHERE id=$1",[x.id]);await c.query('INSERT INTO ledger_entries(payment_id,tontine_id,fund_type,amount) VALUES($1,$2,\'TONTINE_FUNDS\',$3)',[x.id,x.tontine_id,x.base_amount]); if(Number(x.admin_commission)>0) await c.query('INSERT INTO ledger_entries(payment_id,tontine_id,fund_type,amount) VALUES($1,$2,\'ADMIN_COMMISSION\',$3)',[x.id,x.tontine_id,x.admin_commission]); if(Number(x.sponsor_commission)>0) await c.query('INSERT INTO ledger_entries(payment_id,tontine_id,fund_type,amount) VALUES($1,$2,\'SPONSOR_COMMISSION\',$3)',[x.id,x.tontine_id,x.sponsor_commission]);}else if(status==='FAILED')await c.query("UPDATE payments SET status='FAILED' WHERE id=$1",[p.rows[0].id]);await c.query('COMMIT');ok(res,{ok:true})}catch(e){await c.query('ROLLBACK');bad(res,500,'Webhook non traité')}finally{c.release()}});
app.use((req,res)=>bad(res,404,'Route introuvable'));
app.listen(PORT,()=>console.log(`Tontine Digital API :${PORT}`));
